[tool.poetry]
name = "dumb-larklang"
version = "0.1.0"
description = ""
authors = ["Artur Augustyniak <artur@aaugustyniak.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lark = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
